credentials:
  usernames:
    # Tu cuenta de administrador
    admin:
      password: '$2b$12$15tedniBurs5pK.hFSJXT.dbXKWjDsbBR7KRhrppcpsR9arnx.hcW'
    
    # Un usuario médico de ejemplo
    carlos456:
      name: 'Carlos Otiniano Alvarado'
      password: '$2b$12$BpOvWEpPS7MQrXvHBzMhhOBoh1jDCAk/isRaEvHczkc/FAPMwFRmO'

    victor456:
      name: 'Victor Caballero Saravia'
      password: '$2b$12$BpOvWEpPS7MQrXvHBzMhhOBoh1jDCAk/isRaEvHczkc/FAPMwFRmO'

cookie:
  expiry_days: 60 # Días que dura la sesión
  key: 'clave_secreta_para_cookie_123' # Cambia esto por cualquier frase
  name: 'oncoearly_cookie_app'